from pathlib import Path

from src.settings.general import LOG_DIR, PROCESSED_DATA_DIR, INTERIM_DATA_DIR

# ENCODE DATA DIR DEFINITIONS
ENCODE_INTERIM_DATA_DIR = Path("{}/encode".format(INTERIM_DATA_DIR))
ENCODE_PROCESSED_DATA_DIR = Path("{}/encode".format(PROCESSED_DATA_DIR))
DEV_ENCODE_PROCESSED_DATA_DIR = Path("{}/dev".format(ENCODE_PROCESSED_DATA_DIR))
VAL_ENCODE_PROCESSED_DATA_DIR = Path("{}/val".format(ENCODE_PROCESSED_DATA_DIR))

# ENCODE LOG DIR DEFINITIONS
ENCODE_LOG_DIR = Path("{}/encode".format(LOG_DIR))
ENCODE_TRAINING_LOG_FILE = Path("{}/training.log".format(ENCODE_LOG_DIR))
ENCODE_CHECKPOINT_DIR = Path("{}/checkpoints".format(ENCODE_LOG_DIR))
ENCODE_CHECKPOINT_FILES = "{}/cp-{}.ckpt".format(ENCODE_CHECKPOINT_DIR, "{epoch:04d}")

# DATASET SPECIFICATIONS
N_ENCODE_DEV_SAMPLES = 400
N_SAMPLES_IN_TFRECORD = 100
N_ENCODE_VAL_SAMPLES = int(N_ENCODE_DEV_SAMPLES / 4)

# ENCODE MODEL TRAINING SPECIFICATIONS
ENCODE_KERNEL_SIZE = 15
ENCODE_STRIDE = 4
ENCODE_EPOCHS = 20
ENCODE_BATCH_SIZE = 32
